import 'package:cloud_firestore/cloud_firestore.dart';

class FirestoreService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  Future<void> populateCars() async {
    final cars = [
      {
        'carName': 'BMW 2 Series',
        'carClass': 'Coupe',
        'carPower': 255,
        'people': '1-2',
        'bags': '1-4',
        'carImage': 'assets/images/M240i_Sedan.png',
        'carPrice': 45,
        'isRotated': false,
        'carRating': '4.5',
      },
      {
        'carName': 'BMW 3 Series Sedan',
        'carClass': 'Sedan',
        'carPower': 255,
        'people': '1-5',
        'bags': '1-4',
        'carImage': 'assets/images/M340i_Sedan.png',
        'carPrice': 45,
        'isRotated': false,
        'carRating': '4.5',
      },
      {
        'carName': 'BMW 4 Series Coupe',
        'carClass': 'Sedan',
        'carPower': 255,
        'people': '1-2',
        'bags': '1-4',
        'carImage': 'assets/images/M440i_Gran_Coupe.png',
        'carPrice': 45,
        'isRotated': false,
        'carRating': '4.5',
      },
      {
        'carName': 'BMW XM',
        'carClass': 'SUV',
        'carPower': 375,
        'people': '1-5',
        'bags': '1-3',
        'carImage': 'assets/images/XM.png',
        'carPrice': 70,
        'isRotated': true,
        'carRating': '4.7',
      },
      {
        'carName': 'BMW X7',
        'carClass': 'SUV',
        'carPower': 375,
        'people': '1-5',
        'bags': '1-3',
        'carImage': 'assets/images/X7_M60i.png',
        'carPrice': 70,
        'isRotated': true,
        'carRating': '4.7',
      },
      {
        'carName': 'BMW X5M',
        'carClass': 'SUV',
        'carPower': 375,
        'people': '1-5',
        'bags': '1-3',
        'carImage': 'assets/images/X5_M.png',
        'carPrice': 70,
        'isRotated': true,
        'carRating': '4.7',
      },
      {
        'carName': 'BMW X5',
        'carClass': 'SUV',
        'carPower': 375,
        'people': '1-5',
        'bags': '1-3',
        'carImage': 'assets/images/X5_M60i.png',
        'carPrice': 70,
        'isRotated': true,
        'carRating': '4.7',
      },
      {
        'carName': 'BMW X4 M Competition',
        'carClass': 'SUV',
        'carPower': 375,
        'people': '1-5',
        'bags': '1-3',
        'carImage': 'assets/images/X4_M_Competition.png',
        'carPrice': 70,
        'isRotated': true,
        'carRating': '4.7',
      },
      {
        'carName': 'BMW X3',
        'carClass': 'SUV',
        'carPower': 375,
        'people': '1-5',
        'bags': '1-3',
        'carImage': 'assets/images/X3_M40i.png',
        'carPrice': 70,
        'isRotated': true,
        'carRating': '4.7',
      },
      {
        'carName': 'BMW Z4 Roadster',
        'carClass': 'Sport',
        'carPower': 255,
        'people': '1-2',
        'bags': '1-2',
        'carImage': 'assets/images/Z4_M40i.png',
        'carPrice': 55,
        'isRotated': false,
        'carRating': '4.8',
      },
      {
        'carName': 'BMW M8',
        'carClass': 'Sport',
        'carPower': 335,
        'people': '1-5',
        'bags': '1-4',
        'carImage': 'assets/images/M8_Competition_Coupe.png',
        'carPrice': 60,
        'isRotated': true,
        'carRating': '4.6',
      },
      {
        'carName': 'BMW M5',
        'carClass': 'Sport',
        'carPower': 473,
        'people': '1-5',
        'bags': '1-3',
        'carImage': 'assets/images/M5_Sedan.png',
        'carPrice': 80,
        'isRotated': false,
        'carRating': '5.0',
      },
      {
        'carName': 'BMW M4',
        'carClass': 'Sport',
        'carPower': 473,
        'people': '1-5',
        'bags': '1-3',
        'carImage': 'assets/images/M4_Coupe.png',
        'carPrice': 80,
        'isRotated': false,
        'carRating': '5.0',
      },
      {
        'carName': 'BMW M3',
        'carClass': 'Sport',
        'carPower': 473,
        'people': '1-5',
        'bags': '1-3',
        'carImage': 'assets/images/M3_Sedan.png',
        'carPrice': 80,
        'isRotated': false,
        'carRating': '5.0',
      },
      {
        'carName': 'BMW M2',
        'carClass': 'Sport',
        'carPower': 473,
        'people': '1-5',
        'bags': '1-3',
        'carImage': 'assets/images/M2_Competition.png',
        'carPrice': 80,
        'isRotated': false,
        'carRating': '5.0',
      },
    ];

    final batch = _firestore.batch();

    for (var car in cars) {
      final docRef = _firestore.collection('cars').doc(); // Auto-ID
      batch.set(docRef, car);
    }

    await batch.commit();
  }
}
