// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWaNO04NWAswnOWpHVnEnJVWx4RIUSffA',
    appId: '1:465017680457:web:1149cebc120e38ccf1c598',
    messagingSenderId: '465017680457',
    projectId: 'rei-rentals',
    authDomain: 'rei-rentals.firebaseapp.com',
    databaseURL: 'https://rei-rentals-default-rtdb.firebaseio.com',
    storageBucket: 'rei-rentals.firebasestorage.app',
    measurementId: 'G-NQK3Z1WPFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbEC4BeJ2VIfGksEMo0zZq9ZDeHaeMTWY',
    appId: '1:465017680457:android:191d18877a0c4630f1c598',
    messagingSenderId: '465017680457',
    projectId: 'rei-rentals',
    databaseURL: 'https://rei-rentals-default-rtdb.firebaseio.com',
    storageBucket: 'rei-rentals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCek35i-6WDFOevLM_H4PUlXtvGl4gkG3E',
    appId: '1:465017680457:ios:94ef6438efae0afbf1c598',
    messagingSenderId: '465017680457',
    projectId: 'rei-rentals',
    databaseURL: 'https://rei-rentals-default-rtdb.firebaseio.com',
    storageBucket: 'rei-rentals.firebasestorage.app',
    iosBundleId: 'com.example.euroRens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCek35i-6WDFOevLM_H4PUlXtvGl4gkG3E',
    appId: '1:465017680457:ios:94ef6438efae0afbf1c598',
    messagingSenderId: '465017680457',
    projectId: 'rei-rentals',
    databaseURL: 'https://rei-rentals-default-rtdb.firebaseio.com',
    storageBucket: 'rei-rentals.firebasestorage.app',
    iosBundleId: 'com.example.euroRens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWaNO04NWAswnOWpHVnEnJVWx4RIUSffA',
    appId: '1:465017680457:web:14cadddbe64c6bacf1c598',
    messagingSenderId: '465017680457',
    projectId: 'rei-rentals',
    authDomain: 'rei-rentals.firebaseapp.com',
    databaseURL: 'https://rei-rentals-default-rtdb.firebaseio.com',
    storageBucket: 'rei-rentals.firebasestorage.app',
    measurementId: 'G-6G3T0GQRDP',
  );
}
